// ============================================================
// Form constants matching wafid.com/en/book-appointment/
// ============================================================

export const COUNTRIES = [
  { value: 'DZ', label: 'Algeria' },
  { value: 'BD', label: 'Bangladesh' },
  { value: 'BR', label: 'Burundi' },
  { value: 'CM', label: 'Cameroon' },
  { value: 'CL', label: 'Chile' },
  { value: 'CHI', label: 'China' },
  { value: 'EGY', label: 'Egypt' },
  { value: 'ETH', label: 'Ethiopia' },
  { value: 'GN', label: 'Ghana' },
  { value: 'ACT', label: 'India' },
  { value: 'IDN', label: 'Indonesia' },
  { value: 'JR', label: 'Jordan' },
  { value: 'KN', label: 'Kenya' },
  { value: 'LB', label: 'Lebanon' },
  { value: 'MI', label: 'Mali' },
  { value: 'MR', label: 'Morocco' },
  { value: 'NEP', label: 'Nepal' },
  { value: 'NG', label: 'Niger' },
  { value: 'NIG', label: 'Nigeria' },
  { value: 'PAK', label: 'Pakistan' },
  { value: 'PHL', label: 'Philippines' },
  { value: 'SL', label: 'Sierra Leone' },
  { value: 'so', label: 'Somalia' },
  { value: 'Sri', label: 'Sri Lanka' },
  { value: 'SUD', label: 'Sudan' },
  { value: 'SYR', label: 'Syria' },
  { value: 'TNZ', label: 'Tanzania' },
  { value: 'THI', label: 'Thailand' },
  { value: 'TUN', label: 'Tunesia' },
  { value: 'TUR', label: 'Turkey' },
  { value: 'UG', label: 'Uganda' },
  { value: 'YEM', label: 'Yemen' },
];

export const DESTINATION_COUNTRIES = [
  { value: 'BH', label: 'Bahrain' },
  { value: 'KW', label: 'Kuwait' },
  { value: 'OM', label: 'Oman' },
  { value: 'QA', label: 'Qatar' },
  { value: 'SA', label: 'Saudi Arabia' },
  { value: 'UAE', label: 'UAE' },
  { value: 'YEM', label: 'Yemen' },
];

export const NATIONALITIES = [
  { value: '1049', label: 'Afghan' },
  { value: '2', label: 'Albanian' },
  { value: '3', label: 'Algerian' },
  { value: '1070', label: 'Angolan' },
  { value: '8', label: 'Argentinian' },
  { value: '9', label: 'Armenian' },
  { value: '10', label: 'Australian' },
  { value: '11', label: 'Austrian' },
  { value: '12', label: 'Azerbaijani' },
  { value: '14', label: 'Bahraini' },
  { value: '15', label: 'Bangladeshi' },
  { value: '19', label: 'Belarusian' },
  { value: '20', label: 'Belgian' },
  { value: '21', label: 'Belizean' },
  { value: '23', label: 'Bhutanese' },
  { value: '25', label: 'Bosnian' },
  { value: '26', label: 'Brazilian' },
  { value: '30', label: 'Burkinabe' },
  { value: '32', label: 'Burundian' },
  { value: '33', label: 'Cambodian' },
  { value: '34', label: 'Cameroonian' },
  { value: '35', label: 'Canadian' },
  { value: '38', label: 'Chadian' },
  { value: '40', label: 'Chinese' },
  { value: '41', label: 'Colombian' },
  { value: '47', label: 'Cypriot' },
  { value: '48', label: 'Czech' },
  { value: '49', label: 'Danish' },
  { value: '50', label: 'Djibouti' },
  { value: '52', label: 'Dutch' },
  { value: '54', label: 'Ecuadorean' },
  { value: '55', label: 'Egyptian' },
  { value: '58', label: 'Eritrean' },
  { value: '60', label: 'Ethiopian' },
  { value: '177', label: 'Filipino' },
  { value: '63', label: 'Finnish' },
  { value: '64', label: 'French' },
  { value: '68', label: 'German' },
  { value: '69', label: 'Ghanaian' },
  { value: '70', label: 'Greek' },
  { value: '74', label: 'Guinean' },
  { value: '1', label: 'Indian' },
  { value: '81', label: 'Indonesian' },
  { value: '82', label: 'Iranian' },
  { value: '83', label: 'Iraqi' },
  { value: '84', label: 'Irish' },
  { value: '86', label: 'Italian' },
  { value: '87', label: 'Ivorian' },
  { value: '88', label: 'Jamaican' },
  { value: '89', label: 'Japanese' },
  { value: '90', label: 'Jordanian' },
  { value: '91', label: 'Kazakhstani' },
  { value: '92', label: 'Kenyan' },
  { value: '94', label: 'Kuwaiti' },
  { value: '96', label: 'Laotian' },
  { value: '98', label: 'Lebanese' },
  { value: '100', label: 'Libyan' },
  { value: '102', label: 'Lithuanian' },
  { value: '105', label: 'Malagasy' },
  { value: '108', label: 'Maldivian' },
  { value: '109', label: 'Malian' },
  { value: '110', label: 'Maltese' },
  { value: '112', label: 'Mauritanian' },
  { value: '114', label: 'Mexican' },
  { value: '119', label: 'Moroccan' },
  { value: '125', label: 'Nepalese' },
  { value: '127', label: 'New Zealander' },
  { value: '130', label: 'Nigerian' },
  { value: '1073', label: 'Nigerien' },
  { value: '133', label: 'Norwegian' },
  { value: '134', label: 'Omani' },
  { value: '135', label: 'Pakistani' },
  { value: '141', label: 'Peruvian' },
  { value: '142', label: 'Polish' },
  { value: '144', label: 'Qatari' },
  { value: '145', label: 'Romanian' },
  { value: '146', label: 'Russian' },
  { value: '148', label: 'Saudi' },
  { value: '150', label: 'Serbian' },
  { value: '1053', label: 'Sierra Leonean' },
  { value: '152', label: 'Somali' },
  { value: '154', label: 'South Korean' },
  { value: '156', label: 'Sri Lankan' },
  { value: '157', label: 'Sudanese' },
  { value: '189', label: 'Swedish' },
  { value: '159', label: 'Swiss' },
  { value: '160', label: 'Syrian' },
  { value: '161', label: 'Taiwanese' },
  { value: '162', label: 'Tajik' },
  { value: '163', label: 'Tanzanian' },
  { value: '164', label: 'Thai' },
  { value: '194', label: 'Tunisian' },
  { value: '165', label: 'Turkish' },
  { value: '166', label: 'Ugandan' },
  { value: '167', label: 'Ukrainian' },
  { value: '169', label: 'Uzbekistani' },
  { value: '170', label: 'Venezuelan' },
  { value: '171', label: 'Vietnamese' },
  { value: '172', label: 'YEMENI' },
];

export const VISA_TYPES = [
  { value: 'wv', label: 'Work Visa' },
  { value: 'fv', label: 'Family Visa' },
  { value: 'sv', label: 'Study Visa' },
];

export const POSITIONS = [
  { value: '18', label: 'Banking & Finance' },
  { value: '19', label: 'Carpenter' },
  { value: '20', label: 'Cashier' },
  { value: '21', label: 'Electrician' },
  { value: '22', label: 'Engineer' },
  { value: '23', label: 'General Secretory' },
  { value: '24', label: 'Health & Medicine & Nursing' },
  { value: '25', label: 'Heavy Driver' },
  { value: '26', label: 'IT & Internet Engineer' },
  { value: '27', label: 'Leisure & Tourism' },
  { value: '28', label: 'Light Driver' },
  { value: '29', label: 'Mason' },
  { value: '30', label: 'President' },
  { value: '31', label: 'Labour' },
  { value: '32', label: 'Plumber' },
  { value: '33', label: 'Doctor' },
  { value: '34', label: 'Family' },
  { value: '35', label: 'Steel Fixer' },
  { value: '36', label: 'Aluminum Technician' },
  { value: '37', label: 'Nurse' },
  { value: '38', label: 'Male Nurse' },
  { value: '39', label: 'Ward Boy' },
  { value: '40', label: 'Shovel Operator' },
  { value: '41', label: 'Dozer Operator' },
  { value: '42', label: 'Car Mechanic' },
  { value: '43', label: 'Petrol Mechanic' },
  { value: '44', label: 'Diesel Mechanic' },
  { value: '45', label: 'Student' },
  { value: '46', label: 'Accountant' },
  { value: '47', label: 'Lab Technician' },
  { value: '48', label: 'Drafts man' },
  { value: '49', label: 'Auto-Cad Operator' },
  { value: '50', label: 'Painter' },
  { value: '51', label: 'Tailor' },
  { value: '52', label: 'Welder' },
  { value: '53', label: 'X-ray Technician' },
  { value: '54', label: 'Lecturer' },
  { value: '55', label: 'A.C Technician' },
  { value: '56', label: 'Business' },
  { value: '57', label: 'Cleaner' },
  { value: '58', label: 'Security Guard' },
  { value: '59', label: 'House Maid' },
  { value: '60', label: 'Manager' },
  { value: '61', label: 'Hospital Cleaning' },
  { value: '62', label: 'Mechanic' },
  { value: '63', label: 'Computer Operator' },
  { value: '64', label: 'House Driver' },
  { value: '65', label: 'Driver' },
  { value: '66', label: 'Cleaning Labour' },
  { value: '67', label: 'Building Electrician' },
  { value: '68', label: 'Salesman' },
  { value: '69', label: 'Plastermason' },
  { value: '70', label: 'Servant' },
  { value: '71', label: 'Barber' },
  { value: '72', label: 'Residence' },
  { value: '73', label: 'Shepherds' },
  { value: '74', label: 'Employment' },
  { value: '75', label: 'Fuel Filler' },
  { value: '76', label: 'Worker' },
  { value: '77', label: 'House Boy' },
  { value: '78', label: 'House Wife' },
  { value: '79', label: 'RCC Fitter' },
  { value: '80', label: 'Clerk' },
  { value: '81', label: 'Microbiologist' },
  { value: '82', label: 'Teacher' },
  { value: '83', label: 'Helper' },
  { value: '84', label: 'Hajj Duty' },
  { value: '85', label: 'Shuttering' },
  { value: '86', label: 'Supervisor' },
  { value: '87', label: 'Medical Specialist' },
  { value: '88', label: 'Office Secretary' },
  { value: '89', label: 'Technician' },
  { value: '90', label: 'Butcher' },
  { value: '91', label: 'Arabic Food Cook' },
  { value: '92', label: 'Agricultural Worker' },
  { value: '93', label: 'Service' },
  { value: '94', label: 'Studio CAD Designer' },
  { value: '95', label: 'Financial Analyst' },
  { value: '96', label: 'Cabin Appearance (AIR LINES)' },
  { value: '97', label: 'Car Washer' },
  { value: '98', label: 'Surveyor' },
  { value: '99', label: 'Electrical Technician' },
  { value: '100', label: 'Waiter' },
  { value: '103', label: 'Nursing helper' },
  { value: '104', label: 'Anesthesia technician' },
  { value: '107', label: 'Construction worker' },
  { value: '108', label: 'Other' },
];

export const APPOINTMENT_TYPES = [
  { value: 'standard', label: 'Standard Appointment', price: '$10', desc: 'A basic appointment scheduled based on availability.' },
  { value: 'premium', label: 'Premium Appointment', price: '$25', desc: 'Choose your preferred medical center and appointment date.' },
];

export const GENDERS = [
  { value: 'male', label: 'Male' },
  { value: 'female', label: 'Female' },
];

export const MARITAL_STATUSES = [
  { value: 'married', label: 'Married' },
  { value: 'unmarried', label: 'Single' },
];

export const DEFAULT_FORM_VALUES = {
  country: '',
  city: '',
  traveled_country: '',
  appointment_type: 'standard',
  premium_medical_center: '',
  appointment_date: '',
  medical_center: '',
  first_name: '',
  last_name: '',
  dob: '',
  nationality: '',
  gender: '',
  marital_status: '',
  passport: '',
  confirm_passport: '',
  passport_issue_date: '',
  passport_issue_place: '',
  passport_expiry_on: '',
  visa_type: '',
  email: '',
  phone: '',
  national_id: '',
  applied_position: '',
  applied_position_other: '',
};
